#!/bin/sh
set -e

# Code generated by tunneler.io DO NOT EDIT.

if [  -n "$(uname -a | grep Ubuntu)" ]; then
    sudo apt-get update -y 

    curl -s https://api.github.com/repos/tunnelerio/tunneler/releases/latest \
    | grep "browser_download_url.*tunneler-client[^extended].*_Linux_x86_64\.tar\.gz" \
    | cut -d ":" -f 2,3 \
    | tr -d \" \
    | wget -qi -

    tarball="$(find . -name "*Linux_x86_64.tar.gz")"
    tar -xzf $tarball

    chmod +x tunneler-client

    mv tunneler-client /usr/local/bin/

    rm $tarball

    # popd

    location="$(which tunneler-client)"
    echo "tunneler-client binary location: $location"

    # version="$(tunneler-client version)"
    # echo "tunneler-client binary version: $version"

    echo "install openvpn"
    apt-get install openvpn -y

    echo "setting up iptables"
    iptables -I INPUT -p udp --dport 1194 -j ACCEPT
    iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
    sysctl -w net.ipv4.ip_forward=1

    echo "ALL SET!!!"

else
    echo "available on only ubuntu"
fi  
